---
title: "tt-7.8"
format: html
---
```{r}
library(tidyverse)

tuesdata <- tidytuesdayR::tt_load('2025-07-08')
answers <- tuesdata$answers
color_ranks <- tuesdata$color_ranks
users <- tuesdata$users
```

# Filter Answers by Rank
```{r}
purple <- answers |> 
  filter(rank == 1)
green <- answers |> 
  filter(rank == 2)
blue <- answers |> 
  filter(rank == 3)
pink <- answers |> 
  filter(rank == 4)
brown <- answers |> 
  filter(rank == 5)
```

## Plot Gradients for filtered answers
# Blue
```{r}
distinct_blue <- blue %>%
  distinct(hex)

hues <- grDevices::rgb2hsv(grDevices::col2rgb(distinct_blue$hex))["h", ]

distinct_blue <- distinct_blue %>%
  mutate(hue = hues) %>%
  arrange(hue) %>%
  mutate(idx = row_number())

ggplot(distinct_blue, aes(x = idx, y = 1, fill = hex)) +
  geom_tile(height = 0.5) +
  scale_fill_identity() +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_void()
```

# Brown
```{r}
distinct_brown <- brown %>%
  distinct(hex)

hues <- grDevices::rgb2hsv(grDevices::col2rgb(distinct_brown$hex))["h", ]

distinct_brown <- distinct_brown %>%
  mutate(hue = hues) %>%
  arrange(hue) %>%
  mutate(idx = row_number())

ggplot(distinct_brown, aes(x = idx, y = 1, fill = hex)) +
  geom_tile(height = 0.5) +
  scale_fill_identity() +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_void()
```



